const dotenv = require("dotenv");
dotenv.config();

MONGODB_URI = process.env.MONGODB_URI;
PORT = process.env.PORT;
CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

module.exports = {
  MONGODB_URI,
  PORT,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
};
